#------Build Stage---------
FROM golang:1.25 AS builder

WORKDIR /app

COPY . .

RUN go build -o calculator .

#--------Stage 2-------------
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/calculator .

CMD ["./calculator"]
